- name: Systemd daemon-reload
  ansible.builtin.systemd_service:
    daemon-reload: true
  listen: daemon-reload

- name: Restart openwec service
  ansible.builtin.systemd_service:
    name: openwec
    state: restarted
  listen: service-restart
