---
_meta:
  type: "internalusers"
  config_version: 2
admin:
  hash: $2a$12$wrQM9m8KV2fCzAQ748NnN.zeZEbUin2S5jyxLnxJKEmE5Bw0yEooK
  reserved: true
  backend_roles:
  - "admin"
  description: "Demo admin user"
kibanaserver:
  hash: $2a$12$wMLlPCDAkPyaUJJnMoO/lu0N969v78w9hiiVNd/7xK.UPk7EWVsfW
  reserved: true
  description: "Demo kibanaserver user"
kibanaro:
  hash: $2a$12$10X/agnE9u/mv5FflzHzvOUQd5gZTY73uZ4ci2S4aoAUAw8y72zqu
  reserved: false
  backend_roles:
  - "kibanauser"
  - "readall"
  attributes:
    attribute1: "value1"
    attribute2: "value2"
    attribute3: "value3"
  description: "Demo kibanaro user"
logstash:
  hash: $2a$12$pctehs05yKfCB7tZs86pku5ERauNmEYISI8GnHcdPhaRJ9Lx4u9/i
  reserved: false
  backend_roles:
  - "logstash"
  description: "Demo logstash user"
readall:
  hash: $2a$12$xyZLerb73OibIMwHYFkaWuKI3vfEsKt97.p745YpZRA0wlB7hGKNm
  reserved: false
  backend_roles:
  - "readall"
  description: "Demo readall user"
snapshotrestore:
  hash: $2a$12$BFw4cNo0VzHQt6GBCuUgf.AzCk/w7bq477.CQdVDLHwMzz0yV6dfC
  reserved: false
  backend_roles:
  - "snapshotrestore"
  description: "Demo snapshotrestore user"
