- name: Copy pushou script
  ansible.builtin.git:
    repo: 'https://github.com/pushou/siem.git'
    dest: /root/test
    force: true
- name: copy kool script
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/root/test/{{ item }}"
    mode: '0777'
  loop:
    - get_es_passwd.py
    - get_api_key.py
    - create_dc_policy.py
    - create_srv_policy.py
- name: install docker compose and cmake
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker-compose
    - cmake
    - python3-pip
- name: check pip modules
  pip:
    name: "{{ item }}"
  loop:
    - requests
#- name: run pushou scripts
#  become: true
#  ansible.builtin.shell:
#    "{{ item }}"
#  args:
#    chdir: /root/test
#  loop:
#    - "make clean"
#    - "./scripts/lance-ES.sh"
#    - "./scripts/lance-siem.sh"
#    - "./scripts/lance-fleet.sh"
- name: Get elastic password
  become: true
  ansible.builtin.shell:
    "./get_es_passwd.py"
  args:
    chdir: /root/test
  register: elastic_pass
- name: show passwd
  debug:
    msg: "ELS psswd=> {{ elastic_pass.stdout }} on host=> {{ elastic }}"
- name: create api key
  become: true
  ansible.builtin.shell:
    "./get_api_key.py {{ elastic_pass.stdout }} {{ elastic }}"
  args:
    chdir: /root/test
  register: api_key
- name: show api key
  debug:
    msg: "api_key => {{ api_key.stdout }}"
- name: Create DC policy
  ansible.builtin.shell:
    "./create_dc_policy.py {{ elastic_pass.stdout }} {{ api_key.stdout }} {{ elastic }}"
  args:
    chdir: /root/test
  register: dc_token
- name: Create SRV policy
  ansible.builtin.shell:
    "./create_srv_policy.py {{ elastic_pass.stdout }} {{ api_key.stdout }} {{ elastic }}"
  args:
    chdir: /root/test
  register: srv_token
- name: show srv token
  debug:
    msg: "srv token =>{{ srv_token.stdout }}"
- name: show dc token
  debug:  
    msg: "dc token => {{ dc_token.stdout }}"
- name: show api_key
  debug:
    msg: "api_key=>{{ api_key.stdout }}"
- local_action:
    module: copy
    content: "{{ item.var }}"
    dest: "{{ item.path }}" 
  loop:
      - {"path":"~/SAE_CYBER_CLOUD_GROUPE7/roles/GOAD-SRV/files/api_key","var":"{{ api_key.stdout }}"}
      - {"path":"~/SAE_CYBER_CLOUD_GROUPE7/roles/GOAD-DC/files/api_key","var":"{{ api_key.stdout }}"}
      - {"path":"~/SAE_CYBER_CLOUD_GROUPE7/roles/GOAD-DC/files/token","var":"{{ dc_token.stdout }}"}
      - {"path":"~/SAE_CYBER_CLOUD_GROUPE7/roles/GOAD-SRV/files/token","var":"{{ srv_token.stdout }}"}
