- name: Install docker script
  ansible.builtin.get_url:
    url: https://releases.rancher.com/install-docker/20.10.sh
    dest: /tmp
    mode: '0744'
- name: Run docker script
  ansible.builtin.command:
    "/tmp/20.10.sh"
- name: Copy pushou script
  become: true
  ansible.builtin.copy:
    src: {{ item }}
    dst: /tmp
    owner: root
    mode: "711"
  loop:
    - 1  
    - Makefile  
    - README.md  
    - config  
    - docker-compose.yml  
    - etc  
    - lib  
    - scripts
    - templates
    - update.yaml
- name: install docker compose
  ansible.builtin.apt:
    name: docker-compose
    state: present
- name: run pushou scripts
  become: true
  ansible.builtin.shell:
    "make {{ item }}"
  loop:
    - ES
    - siem
    - fleet
