- name: Restart wazuh-indexer
  ansible.builtin.systemd_service:
    name: wazuh-indexer
    state: restarted
  listen: restart-indexer

- name: Restart filebeat
  ansible.builtin.systemd_service:
    name: filebeat
    state: restarted
  listen: restart-filbeat

- name: Restart dashboard
  ansible.builtin.systemd_service:
    name: wazuh-dashboard
    state: restarted
  listen: restart-dashboard
