- name: Install wazuh-manager and filebeat
  become: yes
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - wazuh-manager
    - filebeat

- name: Create filebeat cert directory
  become: yes
  ansible.builtin.file:
    state: directory
    path: /etc/filebeat/certs
    mode: 0500
    owner: root
    group: root
  notify: restart-filbeat

- name: Copy filebeat certs
  become: yes
  ansible.builtin.copy:
    src: "certs/{{ item }}"
    dest: "/etc/filebeat/certs/{{ item }}"
    mode: 0400
    owner: root
    group: root
  loop:
    - wazuh-1.pem
    - wazuh-1-key.pem
    - root-ca.pem
  notify: restart-filbeat

- name: Copy filebeat conf
  become: yes
  ansible.builtin.template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    mode: 0600
    owner: root
    group: root
  notify: restart-filbeat

- name: Get wazuh filebeat template
  become: yes
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/wazuh/wazuh/v4.7.0/extensions/elasticsearch/7.x/wazuh-template.json
    dest: /etc/filebeat/wazuh-template.json
    mode: 0644
    owner: root
    group: root
  notify: restart-filbeat

- name: Get wazuh filebeat modules
  become: yes
  ansible.builtin.unarchive:
    src: https://packages.wazuh.com/4.x/filebeat/wazuh-filebeat-0.3.tar.gz
    dest: /usr/share/filebeat/module/
    remote_src: yes
  notify: restart-filbeat

- name: Start wazuh-manager
  become: yes
  ansible.builtin.systemd_service:
    name: wazuh-manager
    state: started
    enabled: true

- name: Start filebeat
  become: yes
  ansible.builtin.systemd_service:
    name: filebeat
    state: started
    enabled: true
