[logging]

[server]
verbosity = "info"
keytab = "/etc/wec.keytab"

[database]
type = "SQLite"
path = "/var/openwec/db.sqlite"

[[collectors]]
hostname = "open-wec.sevenkingdoms.local"
listen_address = "192.168.56.3"

[collectors.authentication]
type = "Kerberos"
service_principal_name = "http/open-wec.sevenkingdoms.local@SEVENKINGDOMS.LOCAL"
