- name: Install needed packages
  become: yes
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - gnupg
    - apt-transport-https

- name: Install wazuh repos
  become: yes
  ansible.builtin.lineinfile:
    path: "/etc/apt/sources.list.d/wazuh.list"
    line: "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main"
    owner: root
    group: root
    mode: 0644
    create: true

- name: Put wazuh repos key
  become: yes
  ansible.builtin.copy:
    src: wazuh.gpg
    dest: /usr/share/keyrings/wazuh.gpg
    owner: root
    group: root
    mode: 0644
