---
- name: Configure Audit policy on Windows
  hosts: windows

  tasks:
  - name: Enable failure auditing types for all category
    community.windows.win_audit_policy_system:
      category: "{{ item.name }}"
      audit_type: "{{ item.type }}"
    loop:
      - { name: 'Account Logon',      type: 'success, failure' }
      - { name: 'Account Management', type: 'success, failure' }
      - { name: 'Detailed Tracking',  type: 'success, failure' }
      - { name: 'DS Access',          type: 'success, failure' }
      - { name: 'Logon/Logoff',       type: 'success, failure' }
      - { name: 'Object Access',      type: 'none' }
      - { name: 'Policy Change',      type: 'success, failure' }
      - { name: 'Privilege Use',      type: 'none' }
      - { name: 'System',             type: 'success, failure' }
